spring:
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
  # redis 配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 1
server:
  port: 8080
  servlet:
    context-path: /api
  reactive:
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yupao.controller
  # Knife4j v4.0版本针对参数解析ParameterObject的问题说明
  # https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
